### ISSUE TITLE
when I use npm-gif i xxx，i got a error

### ISSUE THREAD

**Issue by leotian** [kodie/npm-gif#2]
![image](https://user-images.githubusercontent.com/10192886/31013425-a2e1e8fc-a548-11e7-862b-73f723460b13.png)

**Comment by kodie** [comment]
Hi @leotian, thank you for bringing this to my attention. This error was due to the [progress-img](https://github.com/kodie/progress-img) dependency not supporting older versions of node. Reinstalling npm-gif with the latest version and updating it's dependencies should fix this issue.
