### ISSUE TITLE
Display messed up on git bash for Windows

### ISSUE THREAD

**Issue by blogdopata** [kodie/npm-gif#4]
You have some video about this ? doesn't work in my git  bash :(

**Comment by kodie** [comment]
Hi @blogdopata, do you receive any errors messages or anything?

**Comment by blogdopata** [comment]
No @kodie , it's strange , yes install the package ,  but the image is not shown.

**Comment by kodie** [comment]
So you installed the package via `npm install --global npm-gif` and when you run `npm-gif install [package]` nothing happens?

**Comment by blogdopata** [comment]
Now it looks like this
![dd](https://user-images.githubusercontent.com/6901412/44001992-450d23ec-9e01-11e8-9adf-e78fde4a0170.png)

**Comment by kodie** [comment]
This seems to be an issue specific to Windows and the Windows terminal.

**Comment by kodie** [comment]
Closing this and moving the conversation over to #3
